export const DATA_PRODUCTS = [
  {
    id: 1,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 2,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 3,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 4,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 5,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 6,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 7,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
  {
    id: 8,
    name: "Gorgeous Apartment Building",
    address: "58 Hullbrook Road, Billesley, B13 0LA",
    price: 7.5,
    beds: 2,
    baths: 2,
    sqft: 1204,
    create_at: 3,
  },
] as const;
